# Generated by Django 4.0.4 on 2022-05-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponto',
            name='data_entrada',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='data_saida',
            field=models.DateTimeField(),
        ),
    ]
