# Generated by Django 4.0.4 on 2022-05-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_alter_ponto_data_entrada_alter_ponto_data_saida'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto',
            name='expediente',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
