# Generated by Django 4.0.4 on 2022-05-14 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_ponto_expediente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='departamento',
        ),
    ]
