# Generated by Django 4.0.4 on 2022-05-14 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0005_departamento_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folhapagamento',
            name='saldo_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
